source 'https://github.com/CocoaPods/Specs.git'

target 'APMultiMenu', :exclusive => true do
  pod "APMultiMenu", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "APMultiMenu", :path => "../"
end
